#+title: 01 Introduction to Networking
#+author: Sajid Mahmood
#+source: Google IT Support Professional Certificate
#+include: The Bits and Bytes of Computer Networking
#+week: Week 01
#+date: <2022-06-03 Fri>
#+options: toc:2

* Introduction to Computer Networking

** Intro

*** Protocol

A defined set of standards that computers must follow in order to communicate properly.

*** Computer Networking

The name we've given to the full scope of how computer communicate with each other.

+ TCP/IP five layered network model

* The TCP/IP Five-Layer Network Model

** 1) Physical Layer

Represents the physical devices that interconnect computers.

+ 10 Base T, 802.11
+ Bits

** 2) Data Link Layer

Responsible for defining a common way of interpreting these signals so network devices can communicate.

+ Ethernet: The Ethernet standards also define a protocol responsible for getting data to nodes on the same network.
+ WIFI
+ Frames
+ Mac Address

** 3) Network Layer

Allows different networks to communicate with each other through devices know as routers.

+ IP: IP is the heart of the Internet and most smaller networks around the world.
+ Datagram
+ IP Address

*** Internetwork

A collection of networks connected together through routers, the most famous of these being the Internet.

** 4) Transport Layer

Sorts out which client and server programs are supposed to get that data.

+ TCP/UDP
+ Segment
+ Port #'s

** 5) Application Layer

There are lots of different protocols at this layer, and as you might have guessed from the name, they are application-specific. Protocols used to allow you to browse the web or send receive email are some common ones.

+ HTTP, SMTP etc.
+ Messages
