#+title: 04 Networking
#+author: Sajid Mahmood
#+source: Google IT Support Professional Certificate
#+include: Technical Support Fundamentals
#+week: Week 4
#+date: <2022-06-02 Thu>
#+options: toc:2

* What is Networking?

** Basics of Networking

*** Network
 An interconnection of Computers.

*** The Internet

The physical connection of computers and wires around the world.

*** The Web

The information present on the Internet.

*** Networking

In an IT field, managing, building, and designing networks.

** Networking Hardware

+ Ethernet Cables
+ WIFI
+ Fiber Optics
+ Router
+ ISP Network
+ Switches and Hubs

*** Network Stack

A set of hardware or software that provides the infrastructure for a computer.

** Language of the Internet

*** IP

Delivers packets to right computers.

*** TCP

Delivers information from one network to another.

** The Web

+ URL
+ Domain Name (registered with ICANN: internet corporation for assigned names and numbers)
+ DNS

* Limitations of the Internet

** History of the Internet

+ 1960s DARPA project introduced with the earliest form of Internet called ARPANET.
+ 1970s invention of TCP/IP made possible the interconnection of computers and different networks.
+ 1990s was the start of World Wide Web (WWW).

** Limitations of the Internet

+ IPV4 addresses are limited, only >4 billion.
+ IPV6 addresses solve this problem with 2^128 addresses, but adaptation is slow and expensive.

*** Network Address Translation (NAT)

Lets organization use one public IP address and many private IP addresses within the network.


* Impact of the Internet

** Impact

*** Globalization

The movement that lets governments, businesses, and organizations communicate and integrate together on an international scale.

** Internet of Things (IOT)

Smart devices like thermostat, refrigerators, and other home appliances as well as every day smart devices which are being connected to the internet thanks to the IOT.

** Privacy and Security

*** GDPR (General Data Protection Regulation)

*** COPPA (Children Online Privacy Protection Act)

*** Copyright Laws

*** Open-source Licenses
