#+title: 05 Software
#+author: Sajid Mahmood
#+source: Google IT Support Professional Certificate
#+include: Technical Support Fundamentals
#+week: Week 2
#+date: <2022-06-02 Thu>
#+options: toc:2

* Introduction to Software

** What is Software?

*** Coding

Translating one language to another.

*** Scripting

Coding in a scripting language.

**** Scripts

Mainly used to perform a single or limited range task.

*** Programming

Coding in a programming language.

*** Programming Languages

Special languages that software developers use to write instructions for computers to execute.

** Types of Software

+ Commercial Software
+ Open-source Software

*** Application Software

Any software created to fulfill a specific need, like a text editor, web browser, or graphic editor.

*** System Software

Software used to keep our core system running, like OS tools and utilities.

*** Firmware

Software that's permanently sotred on a computer component.

** Revisiting abstraction

The concept of taking a complex system and simplifying it for use.

** Recipe for Computer

*** Assembly language

Allowed computer scientists to use human readable instructions, assembled into code, that the machine could understand.

*** Compiled programming languages

Uses human readable instructions, then sends them through a compiler.

*** Interpreted programming languages

The script is run by an interpreter, which interprets the code into CPU instructions just in time to run them.
